site_name: d20age RPG SRD
nav:
  - Início: index.md
  - Personagens:
      - Arcanista: personagens/arcanista.md
      - Combatente: personagens/combatente.md
      - Especialista: personagens/especialista.md
      - Magista: personagens/magista.md
  - Equipamentos e Serviços: equipamentos-e-servicos.md
theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo Escuro
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Modo Claro
      primary: teal
      accent: lime

extra:
  social: 
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@dmquiral5942
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/dm_quiral/
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/fdW435hWdN