site_name: d20age RPG SRD
nav:
  - Início: index.md
  - Personagens:
      - Classes do Jogo:
          - Classes do Jogo: personagens/classes/classes-do-jogo.md
          - Arcanista: personagens/classes/arcanista.md
          - Combatente: personagens/classes/combatente.md
          - Especialista: personagens/classes/especialista.md
          - Magista: personagens/classes/magista.md
      - Povos Fantásticos:
          - Povos Fantásticos: personagens/povos-fantasticos/povos-fantasticos.md
          - Povo Anão: personagens/povos-fantasticos/povo-anao.md
          - Povo Elfo: personagens/povos-fantasticos/povo-elfo.md
          - Povo Gnomo: personagens/povos-fantasticos/povo-gnomo.md
  - Equipamentos e Serviços:
      - Miscelâneas e Utensílios: equipamentos-e-servicos/miscelaneas-e-utensilios.md
      - Armaduras e Escudos: equipamentos-e-servicos/armaduras-e-escudos.md
      - Armas e Munições: equipamentos-e-servicos/armas-e-municoes.md
      - Ervas Medicinais: equipamentos-e-servicos/ervas-medicinais.md
      - Estalagens e Tabernas: equipamentos-e-servicos/estalagens-e-tabernas.md
      - Animais: equipamentos-e-servicos/animais.md
      - Veículos: equipamentos-e-servicos/veiculos.md
      - Máquinas de Guerra: equipamentos-e-servicos/maquinas-de-guerra.md
      - Auxiliares e Profissionais: equipamentos-e-servicos/auxiliares-e-profissionais.md
  - Magia:
      - Regras: magia/regras.md
      - Magias de Primeiro Círculo:
          - Tabela de Magias: magia/1-circulo/__magias-1-circulo.md
          - Aferrolhar: magia/1-circulo/aferrolhar.md
          - Alarme: magia/1-circulo/alarme.md
          - Amarração: magia/1-circulo/amarracao.md
          - Armadura Mágica: magia/1-circulo/armadura-magica.md
          - Detectar Magia: magia/1-circulo/detectar-magia.md
          - Disco Flutuante: magia/1-circulo/disco-flutuante.md
          - Escudo Místico: magia/1-circulo/escudo-mistico.md
          - Emaranhar: magia/1-circulo/emaranhar.md
          - Encantar Pessoas: magia/1-circulo/encantar-pessoas.md
          - Exorcismo: magia/1-circulo/exorcismo.md
          - Flecha Mágica: magia/1-circulo/flecha-magica.md
          - Heroísmo: magia/1-circulo/heroismo.md
          - Leitura Mágica: magia/1-circulo/leitura-magica.md
          - Luz: magia/1-circulo/luz.md
          - Mãos Flamejantes: magia/1-circulo/maos-flamejantes.md
          - Patas de Aranha: magia/1-circulo/patas-de-aranha.md
          - Proteção Contra o Mal: magia/1-circulo/protecao-contra-o-mal.md
          - Restauração: magia/1-circulo/restauracao.md
          - Sono: magia/1-circulo/sono.md
          - Ventriloquismo: magia/1-circulo/ventriloquismo.md
      - Magias de Segundo Círculo:
          - Tabela de Magias: magia/2-circulo/__magias-2-circulo.md
          - Abençoar Arma: magia/2-circulo/abencoar-arma.md
          - Alterar-se: magia/2-circulo/alterar-se.md
          - Desfocar: magia/2-circulo/desfocar.md
          - Invisibilidade: magia/2-circulo/invisibilidade.md
          - Levitar: magia/2-circulo/levitar.md
          - Neutralizar Veneno: magia/2-circulo/neutralizar-veneno.md
          - PES - Percepção Extra Sensorial: magia/2-circulo/pes.md
          - Reflexos: magia/2-circulo/reflexos.md
          - Resistência a Elemento: magia/2-circulo/resistencia-a-elemento.md
          - Silêncio: magia/2-circulo/silencio.md
          - Teia: magia/2-circulo/teia.md
          - Tranca Arcana: magia/2-circulo/tranca-arcana.md
      - Magias de Terceiro Círculo:
          - Tabela de Magias: magia/3-circulo/__magias-3-circulo.md
          - Aceleração: magia/3-circulo/aceleracao.md
          - Bola de Fogo: magia/3-circulo/bola-de-fogo.md
          - Clarividência: magia/3-circulo/clarividencia.md
          - Dissipar Magia: magia/3-circulo/dissipar-magia.md
          - Falar com Mortos: magia/3-circulo/falar-com-mortos.md
          - Imobilizar Pessoas: magia/3-circulo/imobilizar-pessoas.md
          - Respiração Aquática: magia/3-circulo/respiracao-aquatica.md
          - Remover Doença: magia/3-circulo/remover-doenca.md
          - Ultravisão: magia/3-circulo/ultravisao.md
          - Voar: magia/3-circulo/voar.md
      - Magias de Quarto Círculo:
          - Tabela de Magias: magia/4-circulo/__magias-4-circulo.md
          - Encantar Criaturas: magia/4-circulo/encantar-criaturas.md
          - Globo da Invulnerabilidade: magia/4-circulo/globo-da-invulnerabilidade.md
          - Maldição: magia/4-circulo/maldicao.md
          - Medo: magia/4-circulo/medo.md
          - Olho Mágico: magia/4-circulo/olho-magico.md
          - Polimorfismo: magia/4-circulo/polimorfismo.md
          - Porta Dimensional: magia/4-circulo/porta-dimensional.md
          - Terreno Ilusório: magia/4-circulo/terreno-ilusorio.md
      - Magias de Quinto Círculo:
          - Tabela de Magias: magia/5-circulo/__magias-5-circulo.md
          - Animar Mortos: magia/5-circulo/animar-mortos.md
          - Círculo de Teleporte: magia/5-circulo/circulo-de-teleporte.md
          - Conjurar Elemental: magia/5-circulo/conjurar-elemental.md
          - Raio da Morte: magia/5-circulo/raio-da-morte.md
          - Receptáculo: magia/5-circulo/receptaculo.md
          - Telecinésia: magia/5-circulo/telecinesia.md
      - Magias de Sexto Círculo:
          - Tabela de Magias: magia/6-circulo/__magias-6-circulo.md
          - Criar Comida: magia/6-circulo/criar-comida.md
          - Desintegrar: magia/6-circulo/desintegrar.md
          - Petrificação: magia/6-circulo/petrificacao.md
          - Ressureição: magia/6-circulo/ressurreicao.md
  - Manual de Criaturas:
      - Regras: manual-de-criaturas/regras.md
      - Bestas:
          - Índice de Bestas: manual-de-criaturas/bestas/__bestas.md
          - Abelhas Assassinas: manual-de-criaturas/bestas/abelhas-assassinas.md
          - Animais de Montaria: manual-de-criaturas/bestas/animais-de-montaria.md
          - Aranhas Gigantes: manual-de-criaturas/bestas/aranhas-gigantes.md
          - Aves de Rapina: manual-de-criaturas/bestas/aves-de-rapina.md
          - Babuínos da Rocha: manual-de-criaturas/bestas/babuinos-da-rocha.md
          - Besouros: manual-de-criaturas/bestas/besouros.md
          - Cães: manual-de-criaturas/bestas/caes.md
          - Caranguejo Gigante: manual-de-criaturas/bestas/caranguejo-gigante.md
          - Centopeia Gigante: manual-de-criaturas/bestas/centopeia-gigante.md
          - Cobras: manual-de-criaturas/bestas/cobras.md
          - Crocodilos: manual-de-criaturas/bestas/crocodilos.md
          - Cupim Gigante: manual-de-criaturas/bestas/cupim-gigante.md
          - Enxame de Insetos: manual-de-criaturas/bestas/enxame-de-insetos.md
          - Escorpião Gigante: manual-de-criaturas/bestas/escorpiao-gigante.md
          - Formigas Gigantes: manual-de-criaturas/bestas/formigas-gigantes.md
          - Gralhas: manual-de-criaturas/bestas/gralhas.md
          - Javali: manual-de-criaturas/bestas/javali.md
          - Lobos: manual-de-criaturas/bestas/lobos.md
          - Morcegos: manual-de-criaturas/bestas/morcegos.md
          - Polvo Gigante: manual-de-criaturas/bestas/polvo-gigante.md
          - Ratos: manual-de-criaturas/bestas/ratos.md
          - Sapo Gigante: manual-de-criaturas/bestas/sapo-gigante.md
          - Sanguessuga Gigante: manual-de-criaturas/bestas/sanguessuga-gigante.md
          - Tubarões: manual-de-criaturas/bestas/tubaroes.md
          - Ursos: manual-de-criaturas/bestas/ursos.md
      - Construtos:
          - Índice de Construtos: manual-de-criaturas/construtos/__construtos.md
          - Golens: manual-de-criaturas/construtos/golens.md
          - Objetos Animados: manual-de-criaturas/construtos/objetos-animados.md
      - Desmortos:
          - Índice de Desmortos: manual-de-criaturas/desmortos/__desmortos.md
          - Cãoniçal: manual-de-criaturas/desmortos/caonical.md
          - Carniçal: manual-de-criaturas/desmortos/carnical.md
          - Esqueletos: manual-de-criaturas/desmortos/esqueletos.md
          - Espectro: manual-de-criaturas/desmortos/espectro.md
          - Fantasma: manual-de-criaturas/desmortos/fantasma.md
          - Inumano: manual-de-criaturas/desmortos/inumano.md
          - Lich: manual-de-criaturas/desmortos/lich.md
          - Múmia: manual-de-criaturas/desmortos/mumia.md
          - Vampiro: manual-de-criaturas/desmortos/vampiro.md
          - Zumbi: manual-de-criaturas/desmortos/zumbi.md
      - Dracônicos:
          - Índice de Dracônicos: manual-de-criaturas/draconicos/__draconicos.md
          - Dracos: manual-de-criaturas/draconicos/dracos.md
          - Draconato: manual-de-criaturas/draconicos/draconato.md
          - Dragão: manual-de-criaturas/draconicos/dragao.md
          - Hidras: manual-de-criaturas/draconicos/hidras.md
          - Salamandra Ígnea: manual-de-criaturas/draconicos/salamandra-ignea.md
          - Serpe: manual-de-criaturas/draconicos/serpe.md
      - Extraplanares:
          - Índice de Extraplanares: manual-de-criaturas/extraplanares/__extraplanares.md
          - Cão Infernal: manual-de-criaturas/extraplanares/cao-infernal.md
          - Elemental: manual-de-criaturas/extraplanares/elemental.md
          - Gênio: manual-de-criaturas/extraplanares/genio.md
      - Feéricos:
          - Índice de Feéricos: manual-de-criaturas/feericos/__feericos.md
          - Estrigas: manual-de-criaturas/feericos/estrigas.md
          - Fada: manual-de-criaturas/feericos/fada.md
          - Nereídas: manual-de-criaturas/feericos/nereidas.md
          - Ninfa: manual-de-criaturas/feericos/ninfa.md
          - Pégasus: manual-de-criaturas/feericos/pegasus.md
          - Raposa Lampejante: manual-de-criaturas/feericos/raposa-lampejante.md
          - Sátiro: manual-de-criaturas/feericos/satiro.md
          - Trasgo: manual-de-criaturas/feericos/trasgo.md
          - Unicórnio: manual-de-criaturas/feericos/unicornio.md
      - Floranídeos:
          - Índice de Floranídeos: manual-de-criaturas/floranideos/__floranideos.md
          - Cogumelos: manual-de-criaturas/floranideos/cogumelos.md
          - Ente: manual-de-criaturas/floranideos/ente.md
          - Lodo Verde: manual-de-criaturas/floranideos/lodo-verde.md
          - Mofo Amarelo: manual-de-criaturas/floranideos/mofo-amarelo.md
      - Gigantes:
          - Índice de Gigantes: manual-de-criaturas/gigantes/__gigantes.md
          - Ettin: manual-de-criaturas/gigantes/ettin.md
          - Gigantes: manual-de-criaturas/gigantes/gigantes.md
          - Ogro: manual-de-criaturas/gigantes/ogro.md
          - Trol: manual-de-criaturas/gigantes/trol.md
      - Humanoides:
          - Índece de Humanóides: manual-de-criaturas/humanoides/__humanoides.md
          - Anão: manual-de-criaturas/humanoides/anao.md
          - Bandido: manual-de-criaturas/humanoides/bandido.md
          - Centauro: manual-de-criaturas/humanoides/centauro.md
          - Duendes: manual-de-criaturas/humanoides/duendes.md
          - Elfo: manual-de-criaturas/humanoides/elfo.md
          - Gnomo: manual-de-criaturas/humanoides/gnomo.md
          - Guarda Comum: manual-de-criaturas/humanoides/guarda-comum.md
          - Pessoa Comum: manual-de-criaturas/humanoides/pessoa-comum.md
          - Orque: manual-de-criaturas/humanoides/orque.md
          - Troglodita: manual-de-criaturas/humanoides/troglodita.md
          - Veteranos: manual-de-criaturas/humanoides/veteranos.md
      - Monstros:
          - Índce de Monstros: manual-de-criaturas/monstros/__monstros.md
          - Beija-Sangue: manual-de-criaturas/monstros/beija-sangue.md
          - Cocatriz: manual-de-criaturas/monstros/cocatriz.md
          - Cubo Gelatinoso: manual-de-criaturas/monstros/cubo-gelatinoso.md
          - Duplicador: manual-de-criaturas/monstros/duplicador.md
          - Gárgula: manual-de-criaturas/monstros/gargula.md
          - Górgona: manual-de-criaturas/monstros/gorgona.md
          - Gosma Preta: manual-de-criaturas/monstros/gosma-preta.md
          - Grifo: manual-de-criaturas/monstros/grifo.md
          - Licantropo: manual-de-criaturas/monstros/licantropo.md
          - Mímico: manual-de-criaturas/monstros/mimico.md
          - Minotauro: manual-de-criaturas/monstros/minotauro.md
          - Monstro da Ferrugem: manual-de-criaturas/monstros/monstro-da-ferrugem.md
          - Olho Tirano: manual-de-criaturas/monstros/olho-tirano.md
          - Perfurador: manual-de-criaturas/monstros/perfurador.md
          - Quimera: manual-de-criaturas/monstros/quimera.md
          - Sombra: manual-de-criaturas/monstros/sombra.md
          - Urso Coruja: manual-de-criaturas/monstros/urso-coruja.md
          - Verme Carniceiro: manual-de-criaturas/monstros/verme-carniceiro.md
          - Verme Púrpura: manual-de-criaturas/monstros/verme-purpura.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - navigation.instant
    - navigation.path
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo Escuro
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Modo Claro
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@dmquiral5942
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/dm_quiral/
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/fdW435hWdN

markdown_extensions:
  - toc:
      title: Nesta página
