site_name: d20age RPG SRD
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - seracth.suggest
    - search.highlight
    - content.tabs.link
  language: pt-br
  palette:
    - shceme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Escuro
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Modo Claro
      primary: teal
      accent: lime

extra:
  social: 
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@dmquiral5942
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/dm_quiral/
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/fdW435hWdN