site_name: d20age RPG SRD
nav:
  - Início: index.md
  - Personagens:
    - Arcanista: personagens/arcanista.md
    - Combatente: personagens/combatente.md
    - Especialista: personagens/especialista.md
    - Magista: personagens/magista.md
  - Equipamentos e Serviços:
    - Miscelâneas e Utensílios: equipamentos-e-servicos/miscelaneas-e-utensilios.md
    - Armaduras e Escudos: equipamentos-e-servicos/armaduras-e-escudos.md
    - Armas e Munições: equipamentos-e-servicos/armas-e-municoes.md
    - Ervas Medicinais: equipamentos-e-servicos/ervas-medicinais.md
    - Estalagens e Tabernas: equipamentos-e-servicos/estalagens-e-tabernas.md
    - Animais: equipamentos-e-servicos/animais.md
    - Veículos: equipamentos-e-servicos/veiculos.md
    - Máquinas de Guerra: equipamentos-e-servicos/maquinas-de-guerra.md
    - Auziliares e Profissionais: equipamentos-e-servicos/auxiliares-e-profissionais.md
theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo Escuro
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Modo Claro
      primary: teal
      accent: lime

extra:
  social: 
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@dmquiral5942
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/dm_quiral/
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/fdW435hWdN